### ISSUE TITLE
Add .url functionality for Windows

### ISSUE THREAD

**Issue by Nikolassparrow** [sindresorhus/active-win#85] opened 2020-09-23 08:39 UTC
why is it only a thing for macOS users? Could .url be added for windows as well?

**Comment by sindresorhus** [comment] 2020-09-23 11:01
Duplicate of #64

**Comment by sindresorhus** [comment] 2020-09-23 11:01
It's simplify because no one added it.

**Closed by sindresorhus** 2020-09-23 11:01 UTC

**Comment by Nikolassparrow** [comment] 2020-09-23 17:05
could it be added then..?

**Comment by sshah-tilaka** [comment] 2021-09-27 09:21
Dear Sindre Sorhus, I wanted to ask you if there are plans to make the "url" work on Windows platform? Thanks, Sunny
